name: Integration tests

on:
  push:
    branches: [ main, release* ]
  pull_request:
    branches: [ main, release* ]
  schedule:
    # Run tests at 7:00 UTC everyday
    - cron: '0 7 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    name: Python ${{ matrix.python-version }} (nflows=${{ matrix.use-nflows }}) (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os: [macOS, Ubuntu, Windows]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        use-nflows: [True, False]
    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Optionally install nflows
      if: ${{ matrix.use-nflows }}
      run: |
        pip install nflows
    - name: Set nflows version
      run: |
        echo "GLASFLOW_USE_NFLOWS=${{ matrix.use-nflows }}" >> $GITHUB_ENV
    - name: Print environment variables
      run: |
        env
    - name: Run integration tests (fast)
      run: |
        python -m pytest -m "integration_test"
    - name: Run integration tests (slow)
      run: |
        python -m pytest -m "slow_integration_test"
