name: Check nflows fork

on:
  push:
    branches: [ main, release*]
  schedule:
    # Run tests at 7:00 UTC everyday
    - cron: '0 7 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-nflows:
    name: Test (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os: [macOS, Ubuntu, Windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[nflows-test]
    - name: Test with pytest
      run: |
        python -m pytest submodules/nflows
